### ISSUE TITLE
是否考虑提供HTTP接口接收数据推送？

### ISSUE THREAD

**Issue by coosir** [marknown/queueman#1]
这样的话，就是一个完整的队列服务，开发就真正不用和队列直接打交道（每个队列还可以配置KEY做安全校验）

**Comment by marknown** [comment]
你的意思是写队列的操作也用这个中间件来操作？这样比如rabbitmq可能就支持不了fanout等类型了。Redis倒是简单。感谢建议，欢迎回复。

**Comment by coosir** [comment]
是的。我理解就是一个封装，这样中间件可以统一管控队列的写入和消费。

现实情境是比如小型PHP项目，它就不需要相应的扩展去连接RabbitMQ或Redis并进行操作，只需要通过中间件的接口推一次消息就好（当然，会有其他一些参数）

**Comment by marknown** [comment]
我最近几天也想过你的建议，大项目还是直接往队列里插入性能好。小项目，还是比较适合的。我先加入下一版本规划中。

**Comment by coosir** [comment]
谢谢列入考量（对小团队来讲减轻负担和统一规范比对应的性能损耗要更值得）
